---
title: "12.7-Statistical-Learning"
author: "Yuqing Liu"
date: "2023-12-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(glmnet)

set.seed(11)
```


```{r}
bwt_df = 
  read_csv("./birthweight.csv") |> 
  janitor::clean_names() |>
  mutate(
    babysex = as.factor(babysex),
    babysex = fct_recode(babysex, "male" = "1", "female" = "2"),
    frace = as.factor(frace),
    frace = fct_recode(
      frace, "white" = "1", "black" = "2", "asian" = "3", 
      "puerto rican" = "4", "other" = "8"),
    malform = as.logical(malform),
    mrace = as.factor(mrace),
    mrace = fct_recode(
      mrace, "white" = "1", "black" = "2", "asian" = "3", 
      "puerto rican" = "4")) |> 
  sample_n(200)
```

```{r}
x = model.matrix(bwt ~ ., bwt_df)[,-1]
y = bwt_df |> pull(bwt)
```

```{r}
lambda = 10^(seq(3, -2, -0.1))

lasso_fit =
  glmnet(x, y, lambda = lambda)

lasso_cv =
  cv.glmnet(x, y, lambda = lambda)

lambda_opt = lasso_cv$lambda.min
```

```{r}
lasso_fit |> 
  broom::tidy() |> 
  select(term, lambda, estimate) |> 
  complete(term, lambda, fill = list(estimate = 0) ) |> 
  filter(term != "(Intercept)") |> 
  ggplot(aes(x = log(lambda, 10), y = estimate, group = term, color = term)) + 
  geom_path() + 
  geom_vline(xintercept = log(lambda_opt, 10), color = "blue", size = 1.2) +
  theme(legend.position = "none")
```

```{r}
lasso_cv |> 
  broom::tidy() |> 
  ggplot(aes(x = log(lambda, 10), y = estimate)) + 
  geom_point()  
```

```{r}
lasso_fit = 
  glmnet(x, y, lambda = lambda_opt)

lasso_fit |> broom::tidy()
```

```{r}
poke_df = 
  read_csv("./pokemon.csv") |> 
  janitor::clean_names() |> 
  select(hp, speed)
```

```{r}
poke_df |> 
  ggplot(aes(x = hp, y = speed)) + 
  geom_point()
```

```{r}
kmeans_fit =
  kmeans(x = poke_df, centers = 3)
```

```{r}
poke_df =
  broom::augment(kmeans_fit, poke_df)

poke_df |> 
  ggplot(aes(x = hp, y = speed, color = .cluster)) +
  geom_point()
```

```{r}
clusts =
  tibble(k = 2:4) |>
  mutate(
    km_fit =    map(k, \(n_clust) kmeans(poke_df, centers = n_clust)),
    augmented = map(km_fit, \(fit) broom::augment(x = fit, poke_df))
  )

clusts |> 
  select(-km_fit) |> 
  unnest(augmented) |> 
  ggplot(aes(hp, speed, color = .cluster)) +
  geom_point(aes(color = .cluster)) +
  facet_grid(~k)
```

```{r}
library(palmerpenguins)

data("penguins")

penguins = 
  penguins |> 
  select(species, bill_length_mm, flipper_length_mm) |> 
  drop_na() 

penguins |> 
  ggplot(aes(x = bill_length_mm, y = flipper_length_mm, color = species)) + 
  geom_point()

```

```{r}
kmeans_fit =
  penguins |> 
  select(-species) |> 
  scale() |> 
  kmeans(centers = 3)

penguins |> 
  broom::augment(kmeans_fit, data = _) |> 
  ggplot(
    aes(x = bill_length_mm, y = flipper_length_mm,
        color = .cluster, shape = species)) + 
  geom_point(size = 2)
```

```{r}
penguins |> 
  broom::augment(kmeans_fit, data = _) |> 
  count(species, .cluster) |> 
  pivot_wider(
    names_from = .cluster, 
    values_from = n, 
    values_fill = 0)
```

```{r}
traj_data = 
  read_csv("./trajectories.csv")

```

```{r}
traj_data |> 
  ggplot(aes(x = week, y = value, group = subj)) + 
  geom_point() + 
  geom_path()
```

```{r}
int_slope_df = 
  traj_data |> 
  nest(data = week:value) |> 
  mutate(
    models = map(data, \(df) lm(value ~ week, data = df)),
    result = map(models, broom::tidy)
  ) |> 
  select(subj, result) |> 
  unnest(result) |> 
  select(subj, term, estimate) |> 
  pivot_wider(
    names_from = term,
    values_from = estimate
  ) |> 
  rename(int = "(Intercept)", slope = week)
```

```{r}
int_slope_df |> 
  ggplot(aes(x = int, y = slope)) + 
  geom_point()
```

```{r}
km_fit = 
  kmeans(
    x = int_slope_df |> select(-subj) |> scale(), 
    centers = 2)

int_slope_df =
  broom::augment(km_fit, int_slope_df)
```

```{r}
int_slope_df |> 
  ggplot(aes(x = int, y = slope, color = .cluster)) +
  geom_point()
```

```{r}
left_join(traj_data, int_slope_df) |> 
  ggplot(aes(x = week, y = value, group = subj, color = .cluster)) + 
  geom_point() + 
  geom_path() 
```

